### ISSUE TITLE
ConfigError: Missing region in config

### ISSUE THREAD

**Issue by ghost** [Rondineli/serverless-vault-plugin#17]
Hi.
Thank you for the plugin.
I'm trying to run it but getting an error:

```
service: pgaudit
frameworkVersion: '>=1.0.0 <2.0.0'

provider:
...
  environment:
    - SLACK_URL
    - JIRA_TOKEN

functions:
  pgaudit:
...

plugins:
  - serverless-vault-plugin
  - serverless-plugin-scripts

custom:
  vault:
    token: ${env:VAULT_TOKEN}
    url: ${env:VAULT_ADDR}
    secret: "cicd/secret"
    ssl_check: true
    version: "v1"
  kms:
    keyId: ${env:KEY_KMS_ID}
```

Error:

```
  Config Error -------------------------------------------
 
  ConfigError: Missing region in config
      at Request.VALIDATE_REGION (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/event_listeners.js:91:45)
      at Request.callListeners (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
      at callNextListener (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/sequential_executor.js:99:12)
      at /usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/event_listeners.js:85:9
      at finish (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/config.js:322:7)
      at /usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/config.js:340:9
      at EnvironmentCredentials.get (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/credentials.js:126:7)
      at getAsyncCredentials (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/config.js:334:24)
      at Config.getCredentials (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/config.js:354:9)
      at Request.VALIDATE_CREDENTIALS (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/event_listeners.js:80:26)
      at Request.callListeners (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/sequential_executor.js:105:18)
      at Request.emit (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
      at Request.emit (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at Request.runTo (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/request.js:403:15)
      at Request.send (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/request.js:367:10)
      at features.constructor.makeRequest (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/service.js:205:27)
      at features.constructor.svc.<computed> [as encrypt] (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/aws-sdk/lib/service.js:642:23)
      at Promise.then.key (/usr/local/lib/node_modules/serverless-vault-plugin/index.js:41:16)
      at new Promise (<anonymous>)
      at ServerlessPlugin.kmsEncryptVariable (/usr/local/lib/node_modules/serverless-vault-plugin/index.js:35:12)
      at Request._callback (/usr/local/lib/node_modules/serverless-vault-plugin/index.js:124:24)
      at Request.self.callback (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/request/request.js:185:22)
      at Request.emit (events.js:314:20)
      at Request.EventEmitter.emit (domain.js:486:12)
      at Request.<anonymous> (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/request/request.js:1154:10)
      at Request.emit (events.js:314:20)
      at Request.EventEmitter.emit (domain.js:486:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/serverless-vault-plugin/node_modules/request/request.js:1076:12)
      at Object.onceWrapper (events.js:420:28)
      at IncomingMessage.emit (events.js:326:22)
      at IncomingMessage.EventEmitter.emit (domain.js:486:12)
      at endReadableNT (_stream_readable.js:1244:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Do you have any idea what could be wrong here? I tried to paste region everywhere, also tried to add a env var:
```
$ env | grep region -i
AWS_DEFAULT_REGION=eu-west-1
```
It also didn't help.

**Comment by Rondineli** [comment]
Hi @AmetPreply have you tried to use: AWS_REGION instead?

**Comment by ghost** [comment]
Hi.
No, I haven't tried it.
I've fixed that with this workaround:
```
LAMBDA_REGION=$(grep "  region:" serverless.yml | awk '{print $2}')
if [[ ${LAMBDA_REGION} != "" ]]; then
    serverless deploy -r ${LAMBDA_REGION}
fi
```

**Comment by Rondineli** [comment]
It does work as well, this is the serverless framework that needs region, the aws sdk https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html needs it by order of use.

**Comment by Rondineli** [comment]
hence, closing the issue.

Btw: Sorry it took a bit to reply, busy days.
